### PR TITLE
M3 updates

### PR DESCRIPTION
**Pull request by adam-singer**
@mythz want to give this a look and try before I merge it. 

```
Dart Editor version 0.3.1_r17328
Dart SDK version 0.3.1.1_r17328
```

### CODE REVIEW

**Comment by mythz** [comment]
All looks good to me (feel free to merge), just a pending q about changing from optional to named parameters.

**Comment by mythz** [comment]
Also while I have you on the line, is there any chance we can remove the 'dart' prefix from the packages published on pub? e.g change: 

```
http://pub.dartlang.org/packages/dartredisclient
```

to: 

```
http://pub.dartlang.org/packages/redisclient
```

**Comment by adam-singer** [comment]
Sure, I will contact someone at pub and have them delete the dartredisclient package, then we can re upload as redisclient. Need to check if someone else does not already have that package.

**Comment by adam-singer** [comment]
request for delete on dartredisclient http://code.google.com/p/dart/issues/detail?id=8070

**Comment by mythz** [comment]
Awesome, thx Adam.

**Comment by sethladd** [comment]
Thanks!

**Comment by adam-singer** [comment]
@sethladd eventually will hook everything up to drone.io, really impressed today on Dartisians. Using the DrumpRenderTree stuff is excellent.

**Pull request merged**
